---
- block:
    - name: Creates directory
      file:
        path: "outputs/{{ inventory_hostname }}/env_level_commands"
        state: directory
      run_once: true

    - name: IOS run commands and capture
      include_role:
        name: command_capture
      vars:
        command: "{{ item.cmd }}"
        file_name: "{{ item.file }}"
        device_type: ios
        check_type: pre
        category: env_level_commands
      loop: "{{ env_level_commands.ios }}"
