---
- block:
    - name: Initial command
      ios_command:
        commands:
          - "show ip ssh"
      register: output

    - block:
        - name: Checking algorithm
          ios_command:
            commands:
              - "conf t"
              - "no ip ssh server algorithm encryption chacha20-poly1305@openssh.com"
              - "exit"
              - "copy running-config startup-config"
          when: output is defined and 'chacha20-poly1305@openssh.com' in output.stdout[0]

        - name: Checking algorithm
          debug:
            msg: "Algorithm not present"
          when: output is defined and 'chacha20-poly1305@openssh.com' not in output.stdout[0]
